PickleWebStore/PickleWebStore/Models/Member.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace PickleWebStore.Models
{
    public class Member
    {
        public Member()
        {
            IsActive = true; IsDeleted = false; CreationTime = DateTime.Now;
        }
        public int ID { get; set; }
        [Display(Name = "İsim")]
        [Required(ErrorMessage = "Bu alan Boş bırakılamaz.")]
        [StringLength(maximumLength: 75, ErrorMessage = "Bu alan en fazla 75 karakter olmalıdır.")]
        public string Name { get; set; }
        [Display(Name = "Soyisim")]
        [Required(ErrorMessage = "Bu alan Boş bırakılamaz.")]
        [StringLength(maximumLength: 75, ErrorMessage = "Bu alan en fazla 75 karakter olmalıdır.")]
        public string Surname { get; set; }
        [Display(Name = "Kullanıcı Adı")]
        [Required(ErrorMessage = "Bu alan Boş bırakılamaz.")]
        [StringLength(maximumLength: 75, ErrorMessage = "Bu alan en fazla 75 karakter olmalıdır.")]
        public string Username { get; set; }
        [Display(Name = "Mail")]
        [Required(ErrorMessage = "Bu alan Boş bırakılamaz.")]
        [DataType(DataType.EmailAddress)]
        [StringLength(maximumLength: 150, ErrorMessage = "Bu alan en fazla 150 karakter olmalıdır.")]
        public string Mail { get; set; }
        [Display(Name = "Şifre")]
        [Required(ErrorMessage = "Bu alan Boş bırakılamaz.")]
        [StringLength(maximumLength: 20, MinimumLength = 6, ErrorMessage = "Bu alan 6-20 karakter arasında olmalıdır.")]
        public string Password { get; set; }
        [Display(Name = "Kayıt Tarihi")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-mm-yyyy}", ApplyFormatInEditMode = true)]
        public DateTime CreationTime { get; set; }
        [Display(Name = "Son Giriş Tarihi")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-mm-yyyy}", ApplyFormatInEditMode = true)]
        public DateTime LastLoginTime { get; set; }
        [Display(Name = "Durum")]
        public bool IsActive { get; set; }
        [Display(Name = "Silinmiş")]
        public bool IsDeleted { get; set; }
    }
}

PickleWebStore/PickleWebStore/Areas/ManagementPanel/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PickleWebStore;
using PickleWebStore.Areas.ManagementPanel.Filters;
using PickleWebStore.Models;

namespace PickleWebStore.Areas.ManagementPanel.Controllers
{
    [ManagerAuthorizationFilter]
    public class MembersController : Controller
    {
        private PickleWebDBModel db = new PickleWebDBModel();

        // GET: ManagementPanel/Members
        public ActionResult Index()
        {
            return View(db.Members.Where(m=>m.IsDeleted==false).ToList());
        }
        public ActionResult AllIndex()
        {
            return View(db.Members.ToList());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Status(int id, bool isActive)
        {
            var member = db.Members.Find(id);
            if (member != null)
            {
                member.IsActive = !isActive;
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }
        // GET: ManagementPanel/Members/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // POST: ManagementPanel/Members/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Member member = db.Members.Find(id);
            member.IsActive=false;
            member.IsDeleted = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult ReDelete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Products");
            }
            Member prod = db.Members.Find(id);
            if (prod == null)
            {
                return RedirectToAction("NotFound", "SystemMessages");
            }
            prod.IsDeleted = false;
            db.Entry(prod).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PickleWebStore/PickleWebStore/Areas/ManagementPanel/Views/Members/AllIndex.cshtml
@model IEnumerable<PickleWebStore.Models.Member>
@{
    ViewBag.Title = "AllIndex";
    Layout = "~/Areas/ManagementPanel/Views/Shared/_Layout.cshtml";
}

<div class="breadCrumb">
    <a href="@Url.Action("Index", "Home")">Anasayfa</a> >
    <label>Silinen Üyeler</label>
</div>
<div class="pageContent">
    <div class="pagetitle" style="background: linear-gradient(#2e65fc, #3100fc); color: white ">
        <h2 style="margin-top:20px;">Üye Listesi</h2>
        <div style="clear:both"></div>
    </div>
    <div class="tableContent">
        <table class="table">
            <tr style="background-color:#ffdede">
                <th style="border-left:none">
                    @Html.DisplayNameFor(model => model.ID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Surname)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Username)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Mail)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Password)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastLoginTime)
                </th>
                <th>
                    Aktiflik
                </th>
                <th>Seçenekler</th>
            </tr>

            @foreach (var item in Model)
            {
                if (item.IsDeleted)
                {
                    <tr style="background-color:#ffdede">
                        <td style="border-left:none;">
                            @Html.DisplayFor(modelItem => item.ID)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Surname)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Username)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Mail)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Password)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.LastLoginTime)
                        </td>
                        <td style="text-align:center;">
                            @Html.DisplayFor(modelItem => item.IsActive)
                        </td>
                        <td>
                            @Html.ActionLink("Aktifliği Değiştir", "Status", new { id = item.ID }, new { @class = "btnedit" })
                            @Html.ActionLink("Detaylar", "Details", new { id = item.ID }, new { @class = "btndetail" })
                            @Html.ActionLink("Silme işlemini geri al", "ReDelete", new { id = item.ID }, new { @class = "btndetail", @style = "background-color:#973ec1" })
                        </td>
                    </tr>
                }
                
            }

        </table>
    </div>
    <div class="tablefooter">
        <a class="btn-back" style="font-size: 14pt; margin: 10px; padding: 4px; background-color: #007aff; " href="@Url.Action("Index","Members")">Aktif Üyeleri Listele</a>
    </div>
</div>

@section styles
    {
    <link href="~/Areas/ManagementPanel/Assets/css/TableStyle.css" rel="stylesheet" />
}

PickleWebStore/PickleWebStore/Areas/ManagementPanel/Views/Members/Create.cshtml
@model PickleWebStore.Models.Member

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/ManagementPanel/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Member</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreationTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreationTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreationTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastLoginTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastLoginTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastLoginTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsDeleted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsDeleted)
                    @Html.ValidationMessageFor(model => model.IsDeleted, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PickleWebStore/PickleWebStore/Areas/ManagementPanel/Views/Members/Delete.cshtml
@model PickleWebStore.Models.Member

@{
    ViewBag.Title = "Üye Sil";
    Layout = "~/Areas/ManagementPanel/Views/Shared/_Layout.cshtml";
}

<div class="breadCrumb">
    <a href="@Url.Action("Index", "Home")">Anasayfa</a> >
    <a href="@Url.Action("Index", "Mmebers")">Üyeler</a> >
    <label>Üye Sil</label>
</div>

<div class="pageContent">

    <h2 style="margin-left:300px;font-size:25pt;padding:15px 10px;">Üye Sil</h2>
    <hr style="color:silver;width:60%;align-content:center;margin-left:290px;margin-top:6px;" />
    <div style="margin-left:300px;margin-top:20px;">
        <h3 style="margin-bottom: 20px">Bu üyeyi silmek istediğinize emin misiniz?</h3>
        <table border="1" cellpadding="5" cellspacing="0" style="border:1px solid silver" width="600">
            <tr>
                <th align="left" width="30%">ID</th>
                <td>@Model.ID</td>
            </tr>
            <tr>
                <th align="left">Üye Adı</th>
                <td>@Model.Name</td>
            </tr>
            <tr>
                <th align="left">Üye Soyadı</th>
                <td>@Model.Surname</td>
            </tr>
            <tr>
                <th align="left">Kullanıcı Adı</th>
                <td>@Model.Username</td>
            </tr>
            <tr>
                <th align="left">Üye Maili</th>
                <td>@Model.Mail</td>
            </tr>
            <tr>
                <th align="left">Üye Şifresi</th>
                <td>@Model.Password</td>
            </tr>
            <tr>
                <th align="left">Son Giriş Tarihi</th>
                <td>@Model.LastLoginTime</td>
            </tr>
            <tr>
                <th align="left">Kayıt Tarihi</th>
                <td>@Model.CreationTime</td>
            </tr>
            <tr>
                <th align="left">Aktiflik</th>
                <td>
                    @if (@Model.IsActive)
                    {
                        <label>Aktif</label>
                    }
                    else
                    {
                        <label>Deaktif</label>
                    }
                </td>
            </tr>
            <tr>
                <th align="left">Silinme Durumu</th>
                <td>
                    @if (Model.IsDeleted)
                    {
                        <label>Silinmiş</label>
                    }
                    else
                    {
                        <label>Silinmemiş</label>
                    }
                </td>
            </tr>
        </table>
        @using (Html.BeginForm())
        {
            <div class="row">
                @Html.ActionLink("Üye Listesine Dön", "Index", "", new { @class = "btn-back", @style = "margin-left:700px" })
                <input type="submit" value="Üyeyi Sil" class="btn-save" style="background-color:darkred" />
            </div>
            @Html.AntiForgeryToken()
        }

    </div>

</div>

@section styles
{
    <link href="~/Areas/ManagerPanel/Assets/css/FormStyle.css" rel="stylesheet" />
}

PickleWebStore/PickleWebStore/Areas/ManagementPanel/Views/Members/Details.cshtml
@model PickleWebStore.Models.Member

@{
    ViewBag.Title = "Üye Detayı";
    Layout = "~/Areas/ManagementPanel/Views/Shared/_Layout.cshtml";
}

<div class="breadCrumb">
    <a href="@Url.Action("Index", "Home")">Anasayfa</a> >
    <a href="@Url.Action("Index", "Members")">Üyeler</a> >
    <label>Üye Detayı</label>
</div>

<div class="pageContent">

    <h2 style="margin-left:300px;font-size:25pt;padding:15px 10px;">Üye Detayları</h2>
    <hr style="color:silver;width:60%;align-content:center;margin-left:290px;margin-top:6px;" />
    <div style="margin-left:300px;margin-top:20px;">
        <table border="1" cellpadding="5" cellspacing="0" style="border:1px solid silver" width="600">
            <tr>
                <th align="left" width="30%">ID</th>
                <td>@Model.ID</td>
            </tr>
            <tr>
                <th align="left">Üye Adı</th>
                <td>@Model.Name</td>
            </tr>
            <tr>
                <th align="left">Üye Soyadı</th>
                <td>@Model.Surname</td>
            </tr>
            <tr>
                <th align="left">Kullanıcı Adı</th>
                <td>@Model.Username</td>
            </tr>
            <tr>
                <th align="left">Üye Maili</th>
                <td>@Model.Mail</td>
            </tr>
            <tr>
                <th align="left">Üye Şifresi</th>
                <td>@Model.Password</td>
            </tr>
            <tr>
                <th align="left">Son Giriş Tarihi</th>
                <td>@Model.LastLoginTime</td>
            </tr>
            <tr>
                <th align="left">Kayıt Tarihi</th>
                <td>@Model.CreationTime</td>
            </tr>
            <tr>
                <th align="left">Aktiflik</th>
                <td>
                    @if (@Model.IsActive)
                    {
                        <label>Aktif</label>
                    }
                    else
                    {
                        <label>Deaktif</label>
                    }
                </td>
            </tr>
            <tr>
                <th align="left">Silinme Durumu</th>
                <td>
                    @if (Model.IsDeleted)
                    {
                        <label>Silinmiş</label>
                    }
                    else
                    {
                        <label>Silinmemiş</label>
                    }
                </td>
            </tr>
        </table>
        @using (Html.BeginForm())
        {
            <div class="row">
                @Html.ActionLink("Üye Listesine Dön", "Index", "", new { @class = "btn-back", @style = "margin-left:700px" })
               
            </div>
            @Html.AntiForgeryToken()
        }

    </div>

</div>

@section styles
{
    <link href="~/Areas/ManagerPanel/Assets/css/FormStyle.css" rel="stylesheet" />
}

PickleWebStore/PickleWebStore/Areas/ManagementPanel/Views/Members/Edit.cshtml
@model PickleWebStore.Models.Member

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/ManagementPanel/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Member</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreationTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreationTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreationTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastLoginTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastLoginTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastLoginTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsDeleted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsDeleted)
                    @Html.ValidationMessageFor(model => model.IsDeleted, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PickleWebStore/PickleWebStore/Areas/ManagementPanel/Views/Members/Index.cshtml
@model IEnumerable<PickleWebStore.Models.Member>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/ManagementPanel/Views/Shared/_Layout.cshtml";
}

<div class="breadCrumb">
    <a href="@Url.Action("Index", "Home")">Anasayfa</a> >
    <label>Üyeler</label>
</div>
<div class="pageContent">
    <div class="pagetitle" style="background: linear-gradient(#2e65fc, #3100fc); color: white ">
        <h2 style="margin:20px;">Üye Listesi</h2>
        <div style="clear:both"></div>
    </div>
    <div class="tableContent">
        <table class="table">
            <tr>
                <th style="border-left:none">
                    @Html.DisplayNameFor(model => model.ID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Surname)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Username)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Mail)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Password)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastLoginTime)
                </th>
                <th>
                    Aktiflik
                </th>
                <th>Seçenekler</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td style="border-left:none;">
                        @Html.DisplayFor(modelItem => item.ID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Surname)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Username)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Mail)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Password)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastLoginTime)
                    </td>
                    <td style="text-align:center;">
                        @Html.DisplayFor(modelItem => item.IsActive)
                    </td>
                    <td>
                        @using (Html.BeginForm("Status", "Members", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken();
                            @Html.Hidden("id", item.ID);
                            @Html.Hidden("isActive", item.IsActive);
                            if (item.IsActive)
                            {
                                <button type="submit" class="btnedit" style="width:110px;margin-bottom:5px" >
                                    <span>Aktif</span>
                                </button>
                            }
                            else
                            {
                                <button type="submit" class="btndetail" style="background-color: #c89404; width: 110px; margin-bottom: 5px" >
                                    <span>Pasif</span>
                                </button>
                            }

                        }
                        @Html.ActionLink("Detaylar", "Details", new { id = item.ID }, new { @class = "btndetail" })
                        @Html.ActionLink("Sil", "Delete", new { id = item.ID }, new { @class = "btndelete" })
                    </td>
                </tr>
            }

        </table>
    </div>
    <div class="tablefooter">
        <a class="btn-back" style="font-size: 14pt; margin: 10px; padding: 4px; background-color: #ce4747; " href="@Url.Action("AllIndex","Members")">Silinmiş Üyeleri Listele</a>
    </div>
</div>

@section styles
    {
    <link href="~/Areas/ManagementPanel/Assets/css/TableStyle.css" rel="stylesheet" />
}