PickleWebStore/PickleWebStore/Models/Brand.cs
using System.ComponentModel.DataAnnotations;

namespace PickleWebStore.Models
{
    public class Brand
    {
        public Brand()
        {
            IsActive = true; IsDeleted = false;
        }
        //ID isimli kolon otomatik olarak PRIMARY KEY ve IDENTITY(1,1) özelliğine sahip olur.
        public int ID { get; set; }

        [Display(Name = "Marka Adı")]
        //Required attribute'u kolonun veritabanında NOT NULL olmasını sağlar.
        [Required(ErrorMessage = "Bu alan boş bırakılamaz")]
        [StringLength(maximumLength: 150, ErrorMessage = "En fazla 150 karakter olabilir.")]//Kolon nvarchar(150) oldu
        public string Name { get; set; }

        [Display(Name = "Durum")]
        public bool IsActive { get; set; }
        [Display(Name = "Silinmiş")]
        public bool IsDeleted { get; set; }
    }
}

PickleWebStore/PickleWebStore/Areas/ManagementPanel/Controllers/BrandsController.cs
using PickleWebStore.Areas.ManagementPanel.Filters;
using PickleWebStore.Models;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace PickleWebStore.Areas.ManagementPanel.Controllers
{
    [ManagerAuthorizationFilter]
    public class BrandsController : Controller
    {
        private PickleWebDBModel db = new PickleWebDBModel();

        // GET: ManagementPanel/Brands
        public ActionResult Index()
        {
            return View(db.Brands.Where(b => b.IsDeleted == false).ToList());
        }
        public ActionResult AllIndex()
        {
            return View(db.Brands.Where(b => b.IsDeleted == true).ToList());
        }

        // GET: ManagementPanel/Brands/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // GET: ManagementPanel/Brands/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ManagementPanel/Brands/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,IsActive,IsDeleted")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                db.Brands.Add(brand);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(brand);
        }

        // GET: ManagementPanel/Brands/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // POST: ManagementPanel/Brands/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,IsActive,IsDeleted")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                db.Entry(brand).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(brand);
        }

        // GET: ManagementPanel/Brands/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // POST: ManagementPanel/Brands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Brand brand = db.Brands.Find(id);
            brand.IsDeleted = true;
            brand.IsActive = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult ReDelete(int id)
        {
            Brand brand = db.Brands.Find(id);
            brand.IsDeleted = false;
            brand.IsActive = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PickleWebStore/PickleWebStore/Areas/ManagementPanel/Views/Brands/AllIndex.cshtml
@model IEnumerable<PickleWebStore.Models.Brand>

@{
    ViewBag.Title = "Silinen Markalar";
    Layout = "~/Areas/ManagementPanel/Views/Shared/_Layout.cshtml";
}

<div class="breadCrumb">
    <a href="@Url.Action("Index", "Home")">Anasayfa</a> >
    <label>Silinen Markalar</label>
</div>
<div class="pageContent">
    <div class="pagetitle" style="background: linear-gradient(#2e65fc, #3100fc); color: white ">
        <h2 style="margin:20px;">Marka Listesi</h2>
        @Html.ActionLink("Marka Oluştur", "Create")
        <div style="clear:both"></div>
    </div>
    <div class="tableContent">
        <table class="table">
            <tr>
                <th style="border-left:none">
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    Aktiflik
                </th>
                <th>Seçenekler</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr style="background-color: #ffdede">
                    <td style="border-left:none;">
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsActive)
                    </td>
                    <td>
                        @Html.ActionLink("Düzenle", "Edit", new { id = item.ID }, new { @class = "btnedit" })
                        @Html.ActionLink("Silme işlemini geri al", "ReDelete", new { id = item.ID }, new { @class = "btndetail", @style = "background-color:#973ec1" })
                    </td>

                </tr>
            }

        </table>
    </div>
    <div class="tablefooter">
        <a class="btn-back" style=" border-radius: 18px;font-size: 14pt; margin: 10px; padding: 8px; background-color: #007aff " href="@Url.Action("Index","Brands")">Aktif Markaları Listele</a>
    </div>
</div>

@section styles
    {
    <link href="~/Areas/ManagementPanel/Assets/css/TableStyle.css" rel="stylesheet" />
}

PickleWebStore/PickleWebStore/Areas/ManagementPanel/Views/Brands/Create.cshtml
@model PickleWebStore.Models.Brand

@{
    ViewBag.Title = "Marka Oluştur";
    Layout = "~/Areas/ManagementPanel/Views/Shared/_Layout.cshtml";
}

<div class="breadCrumb">
    <a href="@Url.Action("Index", "Home")">Anasayfa</a> >
    <a href="@Url.Action("Index", "Brands")">Markalar</a> >
    <label>Marka Oluştur</label>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2 style="margin-left:300px;font-size:25pt;padding:15px 10px;">Marka Oluştur</h2>
        <hr style="color:silver;width:60%;align-content:center;margin-left:290px;margin-top:6px;" />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="left-part" style="margin-left:650px">
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsActive)
                        @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IsDeleted, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsDeleted)
                        @Html.ValidationMessageFor(model => model.IsDeleted, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div>
                    <div>
                        @Html.ActionLink("Geri Dön", "Index", "", new { @class = "btn-back", @style = "margin-left:100px" })
                        <input type="submit" value="Oluştur" class="btn-save" />
                    </div>

                </div>
            </div>
        </div>
    </div>
}

PickleWebStore/PickleWebStore/Areas/ManagementPanel/Views/Brands/Delete.cshtml
@model PickleWebStore.Models.Brand

@{
    ViewBag.Title = "Sil";
    Layout = "~/Areas/ManagementPanel/Views/Shared/_Layout.cshtml";
}

<div class="breadCrumb">
    <a href="@Url.Action("Index", "Home")">Anasayfa</a> >
    <a href="@Url.Action("Index", "Brands")">Markalar</a> >
    <label>Marka Sil</label>
</div>

<div class="pageContent">

    <h2 style="margin-left:300px;font-size:25pt;padding:15px 10px;">Markayı Sil</h2>
    <hr style="color:silver;width:60%;align-content:center;margin-left:290px;margin-top:6px;" />
    <div style="margin-left:300px;margin-top:20px;">
        <h3 style="margin-bottom: 20px">Bu markayı silmek istediğinize emin misiniz?</h3>
        <table border="1" cellpadding="5" cellspacing="0" style="border:1px solid silver" width="600">
            <tr>
                <th align="left" width="30%">ID</th>
                <td>@Model.ID</td>
            </tr>
            <tr>
                <th align="left">Marka Adı</th>
                <td>@Model.Name</td>
            </tr>

            <tr>
                <th align="left">Aktiflik</th>
                <td>
                    @if (@Model.IsActive)
                    {
                        <label>Aktif</label>
                    }
                    else
                    {
                        <label>Deaktif</label>
                    }
                </td>
            </tr>
            <tr>
                <th align="left">Silinme Durumu</th>
                <td>
                    @if (Model.IsDeleted)
                    {
                        <label>Silinmiş</label>
                    }
                    else
                    {
                        <label>Silinmemiş</label>
                    }
                </td>
            </tr>
        </table>
        @using (Html.BeginForm())
        {
            <div class="row">
                @Html.ActionLink("Marka Listesine Dön", "Index", "", new { @class = "btn-back", @style = "margin-left:700px" })
                <input type="submit" value="Markayı Sil" class="btn-save" style="background-color:darkred" />
            </div>
            @Html.AntiForgeryToken()
        }

    </div>

</div>

@section styles
{
    <link href="~/Areas/ManagerPanel/Assets/css/FormStyle.css" rel="stylesheet" />
}

PickleWebStore/PickleWebStore/Areas/ManagementPanel/Views/Brands/Details.cshtml
@model PickleWebStore.Models.Brand

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/ManagementPanel/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Brand</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PickleWebStore/PickleWebStore/Areas/ManagementPanel/Views/Brands/Edit.cshtml
@model PickleWebStore.Models.Brand

@{
    ViewBag.Title = "Düzenle";
    Layout = "~/Areas/ManagementPanel/Views/Shared/_Layout.cshtml";
}

<div class="breadCrumb">
    <a href="@Url.Action("Index", "Home")">Anasayfa</a> >
    <a href="@Url.Action("Index", "Brands")">Markalar</a> >
    <label>Marka Düzenle</label>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2 style="margin-left:300px;font-size:25pt;padding:15px 10px;">Marka Düzenle</h2>
        <hr style="color:silver;width:60%;align-content:center;margin-left:290px;margin-top:6px;" />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="left-part" style="margin-left:650px">
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsActive)
                        @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IsDeleted, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsDeleted)
                        @Html.ValidationMessageFor(model => model.IsDeleted, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div>
                    <div>
                        @Html.ActionLink("Geri Dön", "Index", "", new { @class = "btn-back", @style = "margin-left:100px" })
                        <input type="submit" value="Düzenle" class="btn-save" />
                    </div>

                </div>
            </div>
        </div>
    </div>
}

PickleWebStore/PickleWebStore/Areas/ManagementPanel/Views/Brands/Index.cshtml
@model IEnumerable<PickleWebStore.Models.Brand>

@{
    ViewBag.Title = "Markalar";
    Layout = "~/Areas/ManagementPanel/Views/Shared/_Layout.cshtml";
}

<div class="breadCrumb">
    <a href="@Url.Action("Index", "Home")">Anasayfa</a> >
    <label>Markalar</label>
</div>
<div class="pageContent">
    <div class="pagetitle" style="background: linear-gradient(#2e65fc, #3100fc); color: white ">
        <h2 style="margin:20px;">Marka Listesi</h2>
        @Html.ActionLink("Marka Oluştur", "Create")
        <div style="clear:both"></div>
    </div>
    <div class="tableContent">
        <table class="table">
            <tr>
                <th style="border-left:none">
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    Aktiflik
                </th>
                <th>Seçenekler</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td style="border-left:none;">
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsActive)
                    </td>
                    <td>
                        @Html.ActionLink("Düzenle", "Edit", new { id = item.ID }, new { @class = "btnedit" })
                        @Html.ActionLink("Sil", "Delete", new { id = item.ID }, new { @class = "btndelete" })
                    </td>

                </tr>
            }

        </table>
    </div>
    <div class="tablefooter">
        <a class="btn-back" style="border-radius: 18px; font-size: 14pt; margin: 10px; padding: 8px; background-color: #ce4747;" href="@Url.Action("AllIndex","Brands")">Silinen Markaları Listele</a>
    </div>
</div>

@section styles
    {
    <link href="~/Areas/ManagementPanel/Assets/css/TableStyle.css" rel="stylesheet" />
}