PickleWebStore/PickleWebStore/Models/Sale.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PickleWebStore.Models
{
    public class Sale
    {
        public Sale()
        {
            IsActive = true; IsDeleted = false; SaleTime = DateTime.Now;
        }
        public int ID { get; set; }
        [Display(Name = "Ürün")]
        public int? Product_ID { get; set; }
        [Display(Name = "Ürün")]
        [ForeignKey("Product_ID")]
        public virtual Product Product { get; set; }
        [Display(Name = "Müşteri")]
        public int? Member_ID { get; set; }
        [Display(Name = "Müşteri")]
        [ForeignKey("Member_ID")]
        public virtual Member Member { get; set; }
        [DataType(DataType.MultilineText)]//View alanında text area oluşturur.
        [StringLength(maximumLength: 500, ErrorMessage = "En fazla 500 karakter olabilir.")]
        [Display(Name = "Teslimat Adresi")]
        public string Address { get; set; }
        [Display(Name = "Satış Fiyatı")]
        public double Price { get; set; }
        [Display(Name = "Adet")]
        public int Quantity { get; set; }
        [Display(Name = "Satış Tutarı")]
        public double TotalPrice { get; set; }
        [Display(Name = "Satış Tarihi")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-mm-yyyy}", ApplyFormatInEditMode = true)]
        public DateTime SaleTime { get; set; }

        [Display(Name = "Durum")]
        public bool IsActive { get; set; }
        //
        [Display(Name = "Silinmiş")]
        public bool IsDeleted { get; set; }
    }
}

PickleWebStore/PickleWebStore/Areas/ManagementPanel/Controllers/SalesController.cs
using PickleWebStore.Areas.ManagementPanel.Filters;
using PickleWebStore.Models;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace PickleWebStore.Areas.ManagementPanel.Controllers
{
    [ManagerAuthorizationFilter]
    public class SalesController : Controller
    {

        private PickleWebDBModel db = new PickleWebDBModel();

        // GET: ManagementPanel/Sales
        public ActionResult Index()
        {
            var sales = db.Sales.Include(s => s.Member).Include(s => s.Product);
            return View(sales.Where(s => s.IsActive == true).ToList());
        }
        public ActionResult AllIndex()
        {
            var sales = db.Sales.Include(s => s.Member).Include(s => s.Product);
            return View(sales.Where(s => s.IsActive == false).ToList());
        }

        // GET: ManagementPanel/Sales/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sale sale = db.Sales.Find(id);
            if (sale == null)
            {
                return HttpNotFound();
            }
            return View(sale);
        }

        // GET: ManagementPanel/Sales/Create
        public ActionResult Create()
        {
            ViewBag.Member_ID = new SelectList(db.Members, "ID", "Name");
            ViewBag.Product_ID = new SelectList(db.Products, "ID", "Barcode");
            return View();
        }

        // POST: ManagementPanel/Sales/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Product_ID,Member_ID,Address,Price,Quantity,TotalPrice,SaleTime,IsActive,IsDeleted")] Sale sale)
        {
            if (ModelState.IsValid)
            {
                db.Sales.Add(sale);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Member_ID = new SelectList(db.Members, "ID", "Name", sale.Member_ID);
            ViewBag.Product_ID = new SelectList(db.Products, "ID", "Barcode", sale.Product_ID);
            return View(sale);
        }

        // GET: ManagementPanel/Sales/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sale sale = db.Sales.Find(id);
            if (sale == null)
            {
                return HttpNotFound();
            }
            ViewBag.Member_ID = new SelectList(db.Members, "ID", "Name", sale.Member_ID);
            ViewBag.Product_ID = new SelectList(db.Products, "ID", "Barcode", sale.Product_ID);
            return View(sale);
        }

        // POST: ManagementPanel/Sales/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Product_ID,Member_ID,Address,Price,Quantity,TotalPrice,SaleTime,IsActive,IsDeleted")] Sale sale)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sale).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Member_ID = new SelectList(db.Members, "ID", "Name", sale.Member_ID);
            ViewBag.Product_ID = new SelectList(db.Products, "ID", "Barcode", sale.Product_ID);
            return View(sale);
        }

        // GET: ManagementPanel/Sales/Delete/5
        public ActionResult Delete(int? id)
        {
            Sale sale = db.Sales.Find(id);

            sale.IsActive = false;

            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult ReDelete(int id)
        {
            Sale sale = db.Sales.Find(id);

            sale.IsActive = true;

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PickleWebStore/PickleWebStore/Areas/ManagementPanel/Views/Sales/AllIndex.cshtml
@model IEnumerable<PickleWebStore.Models.Sale>

@{
    ViewBag.Title = "Tamamlanan Satislar";
    Layout = "~/Areas/ManagementPanel/Views/Shared/_Layout.cshtml";
}

<div class="breadCrumb">
    <a href="@Url.Action("Index", "Home")">Anasayfa</a> >
    <label>Tamamlanan Satışlar</label>
</div>
<div class="pageContent">
    <div class="pagetitle" style="background: linear-gradient(#2e65fc, #3100fc); color: white ">
        <h2 style="margin:20px;">Tamamlanan Satış Listesi</h2>
        <div style="clear:both"></div>
    </div>
    <div class="tableContent">
        <table class="table">
            <tr>
                <th>
                    Müşteri Adı
                </th>
                <th>
                    Ürün Adı
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Quantity)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TotalPrice)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SaleTime)
                </th>
                <th>
                    İşlem Durumu
                </th>

                <th>Seçenekler</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr style="background-color: #9eea9d">
                    <td>
                        @Html.DisplayFor(modelItem => item.Member.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Product.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TotalPrice)
                    </td>
                    <td>
                        @item.SaleTime
                    </td>
                    <td>
                        @if (!item.IsActive)
                        {
                            <span>Tamamlandı</span>
                        }
                        else
                        {
                            <span>Devam Ediyor</span>
                        }
                    </td>
                    <td >
                        @Html.ActionLink("Detaylar", "Details", new { id = item.ID }, new { @class = "btndetail" })
                        @Html.ActionLink("İşleme Al", "ReDelete", new { id = item.ID }, new { @class = "btndetail" , @style= "background-color:#ff6a00" })
                    </td>
                </tr>
            }

        </table>
    </div>
    <div class="tablefooter">
        <a class="btn-back" style=" border-radius: 3px; font-size: 14pt; margin: 10px; padding: 8px; background-color: #ce4747 " href="@Url.Action("Index","Sales")">Aktif İşlemleri Listele</a>
    </div>
</div>

@section styles
    {
    <link href="~/Areas/ManagementPanel/Assets/css/TableStyle.css" rel="stylesheet" />
}

PickleWebStore/PickleWebStore/Areas/ManagementPanel/Views/Sales/Details.cshtml
@model PickleWebStore.Models.Sale

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/ManagementPanel/Views/Shared/_Layout.cshtml";
}

<div class="breadCrumb">
    <a href="@Url.Action("Index", "Home")">Anasayfa</a> >
    <a href="@Url.Action("Index", "Sales")">Satışlar</a> >
    <label>Satış Detayı</label>
</div>

<div class="pageContent">

    <h2 style="margin-left:300px;font-size:25pt;padding:15px 10px;">Satış Detayları</h2>
    <hr style="color:silver;width:60%;align-content:center;margin-left:290px;margin-top:6px;" />
    <div style="margin-left:300px;margin-top:20px;">
        <table border="1" cellpadding="5" cellspacing="0" style="border:1px solid silver" width="600">
            <tr>
                <th align="left" width="30%">ID</th>
                <td>@Model.ID</td>
            </tr>
            <tr>
                <th align="left">Üye Adı</th>
                <td>@Model.Member.Username</td>
            </tr>
            <tr>
                <th align="left">Ürün ADI</th>
                <td>@Model.Product.Name</td>
            </tr>
            <tr>
                <th align="left">Adres</th>
                <td>@Model.Address</td>
            </tr>
            <tr>
                <th align="left">Üye Maili</th>
                <td>@Model.Member.Mail</td>
            </tr>
            <tr>
                <th align="left">Satış Fiyatı</th>
                <td>@Model.Price</td>
            </tr>
            <tr>
                <th align="left">Adet</th>
                <td>@Model.Quantity</td>
            </tr>
            <tr>
                <th align="left">Toplam Tutar</th>
                <td>@Model.TotalPrice</td>
            </tr>
            <tr>
                <th align="left">Satış Tarihi</th>
                <td>@Model.SaleTime</td>
            </tr>
            <tr>
                <th align="left">Aktiflik</th>
                <td>
                    @if (@Model.IsActive)
                    {
                        <label>Aktif</label>
                    }
                    else
                    {
                        <label>Deaktif</label>
                    }
                </td>
            </tr>
            <tr>
                <th align="left">Silinme Durumu</th>
                <td>
                    @if (Model.IsDeleted)
                    {
                        <label>Silinmiş</label>
                    }
                    else
                    {
                        <label>Silinmemiş</label>
                    }
                </td>
            </tr>
        </table>
        @using (Html.BeginForm())
        {
            <div class="row">
                @Html.ActionLink("Satış Listesine Dön", "Index", "", new { @class = "btn-back", @style = "margin-left:700px" })

            </div>
            @Html.AntiForgeryToken()
        }

    </div>

</div>

@section styles
{
    <link href="~/Areas/ManagerPanel/Assets/css/FormStyle.css" rel="stylesheet" />
}</p>

PickleWebStore/PickleWebStore/Areas/ManagementPanel/Views/Sales/Edit.cshtml
@model PickleWebStore.Models.Sale

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/ManagementPanel/Views/Shared/_Layout.cshtml";
}

<div class="breadCrumb">
    <a href="@Url.Action("Index", "Home")">Anasayfa</a> >
    <a href="@Url.Action("Index", "Sales")">Satışlar</a> >
    <label>Satış Düzenle</label>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    @Html.HiddenFor(model => model.IsDeleted);@Html.HiddenFor(model => model.Product_ID);
    @Html.HiddenFor(model => model.Member_ID);@Html.HiddenFor(model => model.Price);
    @Html.HiddenFor(model => model.TotalPrice);@Html.HiddenFor(model => model.Quantity);
    <div class="form-horizontal">
        <h2 style="margin-left:300px;font-size:25pt;padding:15px 10px;">Satışı Düzenle</h2>
        <hr style="color:silver;width:60%;align-content:center;margin-left:290px;margin-top:6px;" />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="left-part" style="margin-left:400px;min-width:300px">
            <div class="form-group">
                @Html.LabelFor(model => model.Product.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Model.Product.Name
                </div>
            </div>

            <div class="form-group">
                <label class = "control-label col-md-2"> Sipariş Eden</label>
                <div class="col-md-10">
                    @Model.Member.Name @Model.Member.Surname
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div>
                        @Model.Price TL
                    </div>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div >
                        @Model.Quantity
                    </div>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.TotalPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div >
                        @Model.TotalPrice TL
                    </div>
                </div>
            </div>
        </div>
        <div class="right-part">
            <div class="form-group">
                @Html.LabelFor(model => model.SaleTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div >
                        @Model.SaleTime
                    </div>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsActive)
                        @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div>
                    <div>
                        @Html.ActionLink("Geri Dön", "Index", "", new { @class = "btn-back", @style = "margin-left:100px" })
                        <input type="submit" value="Düzenle" class="btn-save" />
                    </div>

                </div>
            </div>
        </div>
    </div>

}

PickleWebStore/PickleWebStore/Areas/ManagementPanel/Views/Sales/Index.cshtml
@model IEnumerable<PickleWebStore.Models.Sale>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/ManagementPanel/Views/Shared/_Layout.cshtml";
}

<div class="breadCrumb">
    <a href="@Url.Action("Index", "Home")">Anasayfa</a> >
    <label>Satışlar</label>
</div>
<div class="pageContent">
    <div class="pagetitle" style="background: linear-gradient(#2e65fc, #3100fc); color: white ">
        <h2 style="margin:20px;">Satış Listesi</h2>
        <div style="clear:both"></div>
    </div>
    <div class="tableContent">
        <table class="table">
            <tr>
                <th>
                    Müşteri Adı
                </th>
                <th>
                    Ürün Adı
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Quantity)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TotalPrice)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SaleTime)
                </th>
                <th>
                    İşlem Durumu
                </th>

                <th>Seçenekler</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Member.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Product.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TotalPrice)
                    </td>
                    <td>
                        @item.SaleTime
                    </td>
                    <td>
                        @if (!item.IsActive)
                        {
                            <span>Tamamlandı</span>
                        }
                        else
                        {
                            <span>Devam Ediyor</span>
                        }
                    </td>
                    <td>
                        @Html.ActionLink("Düzenle", "Edit", new { id = item.ID }, new { @class = "btnedit" })
                                        @Html.ActionLink("Detaylar", "Details", new { id = item.ID }, new { @class = "btndetail" })
                                        @Html.ActionLink("Tamamlandı", "Delete", new { id = item.ID }, new { @class = "btndelete" })
                                    </td>
                </tr>
            }

        </table>
    </div>
    <div class="tablefooter">
        <a class="btn-back" style=" border-radius: 3px; font-size: 14pt; margin: 10px; padding: 8px; background-color: #4fba4e " href="@Url.Action("AllIndex","Sales")">Tamamlanan İşlemleri Listele</a>
    </div>
</div>

@section styles
    {
    <link href="~/Areas/ManagementPanel/Assets/css/TableStyle.css" rel="stylesheet" />
}